# Generated by Django 4.2.5 on 2024-05-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gmail', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=50)),
                ('is_verify', models.CharField(default=False, max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(max_length=100)),
                ('service_price', models.IntegerField()),
                ('service_package', models.CharField(max_length=100)),
                ('service_tax', models.IntegerField()),
                ('service_image', models.ImageField(upload_to='service/')),
            ],
        ),
    ]
