# Generated by Django 4.2.5 on 2024-05-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='admin_access',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
