# Generated by Django 4.2.5 on 2024-05-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_register_admin_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='admin_access',
            new_name='admin',
        ),
    ]
