# Generated by Django 4.2.5 on 2023-12-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gmail',
            field=models.CharField(default='satyanarayanbairwa033@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='123@abc', max_length=100),
        ),
    ]
